spring.application.name:

server.port: 8080

spring:
  config:
    activate.on-profile: default
  application.name: voting-service

  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/voting?rewriteBatchedStatements=true&useTimezone=true&serverTimezone=America/Recife
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:password}

    hikari:
      connectionTimeout: 30000
      idleTimeout: 10000
      maxLifetime: 60000
      maximumPoolSize: 8
      leakDetectionThreshold: 60000

  data:
    redis:
      database: 0
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace

---
#Profile test

spring:
  config:
    activate.on-profile: test